CREATE TABLE [dqm].[test_case] (
    [test_uid]              VARCHAR (200)  NOT NULL,
    [measure_name]          VARCHAR (200)  NOT NULL,
    [precision]             INT            NULL,
    [expected_value]        FLOAT (53)     NULL,
    [expected_text]         VARCHAR (200)  NULL,
    [actual_value]          FLOAT (53)     NULL,
    [actual_text]           VARCHAR (200)  NULL,
    [result_variance]       FLOAT (53)     NULL,
    [result_variance_rate]  FLOAT (53)     NULL,
    [allowed_variance]      FLOAT (53)     NULL,
    [allowed_variance_rate] FLOAT (53)     NULL,
    [failure_flag]          CHAR (1)       NULL,
    [grain_hash]            VARCHAR (2000) NULL,
    [grain_01_name]         VARCHAR (200)  NULL,
    [grain_01_text]         VARCHAR (200)  NULL,
    [grain_02_name]         VARCHAR (200)  NULL,
    [grain_02_text]         VARCHAR (200)  NULL,
    [grain_03_name]         VARCHAR (200)  NULL,
    [grain_03_text]         VARCHAR (200)  NULL,
    [grain_04_name]         VARCHAR (200)  NULL,
    [grain_04_text]         VARCHAR (200)  NULL,
    [grain_05_name]         VARCHAR (200)  NULL,
    [grain_05_text]         VARCHAR (200)  NULL,
    [create_dtm]            DATETIME       DEFAULT (getdate()) NULL
);

