CREATE TABLE [cdm].[batch] (
    [batch_key]                   INT           NOT NULL,
    [process_uid]                 VARCHAR (100)  NOT NULL,
    [status]                      VARCHAR (100)  NULL,
    [completed_ind]               BIT           DEFAULT ((0)) NULL,
    [initiate_dtm]                DATETIME      NULL,
    [conclude_dtm]                DATETIME      NULL,
    [duration_sec]                AS            (CONVERT([decimal](20,3),datediff(millisecond,[initiate_dtm],[conclude_dtm])/(1000.0))),
    [source_record_ct]            INT           NULL,
    [inserted_record_ct]          INT           NULL,
    [updated_record_ct]           INT           NULL,
    [deleted_record_ct]           INT           NULL,
    [advanced_version_record_ct]  INT           NULL,
    [collapsed_version_record_ct] INT           NULL,
    [revised_record_ct]           INT           NULL,
    [unprocessed_record_ct]       INT           NULL,
    [exception_record_ct]         INT           NULL,
    [current_sequence_key]        BIGINT        NULL,
    [current_sequence_dtm]        DATETIME      NULL,
    [prior_batch_key]             INT           NULL,
    [start_sequence_key]          BIGINT        NULL,
    [start_sequence_dtm]          DATETIME      NULL,
    [limit_process_uid]           VARCHAR (50)  NULL,
    [limit_batch_key]             INT           NULL,
    [end_sequence_key]            BIGINT        NULL,
    [end_sequence_dtm]            DATETIME      NULL,
    [workflow_name]               VARCHAR (200) NULL,
    [workflow_guid]               VARCHAR (100) NULL,
    [workflow_version]            VARCHAR (200) NULL,
    [comments]                    VARCHAR (200) NULL,
    CONSTRAINT [batch_pk] PRIMARY KEY CLUSTERED ([batch_key] ASC)
);

