USE [$(FileManagementDB_Name)]
GO

TRUNCATE TABLE [dbo].[attribute]

INSERT [dbo].[attribute]  VALUES (N'agency', 'DT_STR', 100, GETDATE(), GETDATE(), 0)
INSERT [dbo].[attribute]  VALUES (N'agency_location', 'DT_STR', 100, GETDATE(), GETDATE(), 0)
INSERT [dbo].[attribute]  VALUES (N'agency_location_alias', 'CHAR', 5, GETDATE(), GETDATE(), 0)
INSERT [dbo].[attribute]  VALUES (N'team', 'DT_STR', 20, GETDATE(), GETDATE(), 0)
INSERT [dbo].[attribute]  VALUES (N'patient_lastname', 'DT_STR', 50, GETDATE(), GETDATE(), 0)
INSERT [dbo].[attribute]  VALUES (N'patient_firstname', 'DT_STR', 50, GETDATE(), GETDATE(), 0)
INSERT [dbo].[attribute]  VALUES (N'MRN', 'DT_STR', 50, GETDATE(), GETDATE(), 0)
INSERT [dbo].[attribute]  VALUES (N'oasis_visit_type', 'DT_STR', 50, GETDATE(), GETDATE(), 0)
INSERT [dbo].[attribute]  VALUES (N'visit_type', 'DT_STR', 50, GETDATE(), GETDATE(), 0)
INSERT [dbo].[attribute]  VALUES (N'assessment_dt', 'DT_DBDATE', NULL, GETDATE(), GETDATE(), 0)
INSERT [dbo].[attribute]  VALUES (N'responsible_position', 'DT_STR', 50, GETDATE(), GETDATE(), 0)
INSERT [dbo].[attribute]  VALUES (N'arrival_dt', 'DT_DBDATE', NULL, GETDATE(), GETDATE(), 0)
INSERT [dbo].[attribute]  VALUES (N'SOE_dt', 'DT_DBDATE', NULL, GETDATE(), GETDATE(), 0)
INSERT [dbo].[attribute]  VALUES (N'SOC_dt', 'DT_DBDATE', NULL, GETDATE(), GETDATE(), 0)
INSERT [dbo].[attribute]  VALUES (N'REC_dt', 'DT_DBDATE', NULL, GETDATE(), GETDATE(), 0)
INSERT [dbo].[attribute]  VALUES (N'ROC_dt', 'DT_DBDATE', NULL, GETDATE(), GETDATE(), 0)
INSERT [dbo].[attribute]  VALUES (N'hospice_dt', 'DT_DBDATE', NULL, GETDATE(), GETDATE(), 0)
INSERT [dbo].[attribute]  VALUES (N'discharge_dt', 'DT_DBDATE', NULL, GETDATE(), GETDATE(), 0)
INSERT [dbo].[attribute]  VALUES (N'payor_type', 'DT_STR', 50, GETDATE(), GETDATE(), 0)
INSERT [dbo].[attribute]  VALUES (N'payor_source', 'DT_STR', 50, GETDATE(), GETDATE(), 0)
INSERT [dbo].[attribute]  VALUES (N'secondary_payor_type', 'DT_STR', 50, GETDATE(), GETDATE(), 0)
INSERT [dbo].[attribute]  VALUES (N'secondary_payor_source', 'DT_STR', 50, GETDATE(), GETDATE(), 0)
INSERT [dbo].[attribute]  VALUES (N'clinician_firstname', 'DT_STR', 50, GETDATE(), GETDATE(), 0)
INSERT [dbo].[attribute]  VALUES (N'clinician_lastname', 'DT_STR', 50, GETDATE(), GETDATE(), 0)
INSERT [dbo].[attribute]  VALUES (N'event', 'DT_STR', 50, GETDATE(), GETDATE(), 0)
INSERT [dbo].[attribute]  VALUES (N'stage', 'DT_STR', 50, GETDATE(), GETDATE(), 0)
INSERT [dbo].[attribute]  VALUES (N'task', 'DT_STR', 50, GETDATE(), GETDATE(), 0)
----------------------------------------------------------------------------------------------------------------
--INSERT [dbo].[attribute]  VALUES (N'Agency', 'DT_STR', 100, GETDATE(), GETDATE(), 0)
--INSERT [dbo].[attribute]  VALUES (N'Agency_Location', 'DT_STR', 100, GETDATE(), GETDATE(), 0)  --DT_WSTR, string[DT_STR]
--INSERT [dbo].[attribute]  VALUES (N'Branch', 'CHAR', 5, GETDATE(), GETDATE(), 0)   --database date[DT_DBDATE]
--INSERT [dbo].[attribute]  VALUES (N'Team', 'DT_STR', 20, GETDATE(), GETDATE(), 0)
--INSERT [dbo].[attribute]  VALUES (N'ClientLastname', 'DT_STR', 50, GETDATE(), GETDATE(), 0)
--INSERT [dbo].[attribute]  VALUES (N'ClientFirstname', 'DT_STR', 50, GETDATE(), GETDATE(), 0)
--INSERT [dbo].[attribute]  VALUES (N'MRNo', 'DT_STR', 50, GETDATE(), GETDATE(), 0)
--INSERT [dbo].[attribute]  VALUES (N'OASISVisitType', 'DT_STR', 50, GETDATE(), GETDATE(), 0)
--INSERT [dbo].[attribute]  VALUES (N'VisitType', 'DT_STR', 50, GETDATE(), GETDATE(), 0)
--INSERT [dbo].[attribute]  VALUES (N'VisitDate', 'DT_DBDATE', NULL, GETDATE(), GETDATE(), 0)
--INSERT [dbo].[attribute]  VALUES (N'ResponsiblePosition', 'DT_STR', 50, GETDATE(), GETDATE(), 0)
--INSERT [dbo].[attribute]  VALUES (N'Arrived', 'DT_DBDATE', NULL, GETDATE(), GETDATE(), 0)
--INSERT [dbo].[attribute]  VALUES (N'SOEDate', 'DT_DBDATE', NULL, GETDATE(), GETDATE(), 0)
--INSERT [dbo].[attribute]  VALUES (N'SOCDate', 'DT_DBDATE', NULL, GETDATE(), GETDATE(), 0)
--INSERT [dbo].[attribute]  VALUES (N'RECDate', 'DT_DBDATE', NULL, GETDATE(), GETDATE(), 0)
--INSERT [dbo].[attribute]  VALUES (N'ROCDate', 'DT_DBDATE', NULL, GETDATE(), GETDATE(), 0)
--INSERT [dbo].[attribute]  VALUES (N'HospiceDate', 'DT_DBDATE', NULL, GETDATE(), GETDATE(), 0)
--INSERT [dbo].[attribute]  VALUES (N'DischargeDate', 'DT_DBDATE', NULL, GETDATE(), GETDATE(), 0)
--INSERT [dbo].[attribute]  VALUES (N'PayorType', 'DT_STR', 50, GETDATE(), GETDATE(), 0)
--INSERT [dbo].[attribute]  VALUES (N'PayorSource', 'DT_STR', 50, GETDATE(), GETDATE(), 0)
--INSERT [dbo].[attribute]  VALUES (N'SecondaryPayorType', 'DT_STR', 50, GETDATE(), GETDATE(), 0)
--INSERT [dbo].[attribute]  VALUES (N'SecondaryPayorSource', 'DT_STR', 50, GETDATE(), GETDATE(), 0)
--INSERT [dbo].[attribute]  VALUES (N'ClinicianFirstName', 'DT_STR', 50, GETDATE(), GETDATE(), 0)
--INSERT [dbo].[attribute]  VALUES (N'ClinicianLastName', 'DT_STR', 50, GETDATE(), GETDATE(), 0)
--INSERT [dbo].[attribute]  VALUES (N'Event', 'DT_STR', 50, GETDATE(), GETDATE(), 0)
--INSERT [dbo].[attribute]  VALUES (N'Stage', 'DT_STR', 50, GETDATE(), GETDATE(), 0)
--INSERT [dbo].[attribute]  VALUES (N'Task', 'DT_STR', 50, GETDATE(), GETDATE(), 0)
--NUMERIC
--STRING
